# Generated by Django 4.1.7 on 2023-04-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='Organization'),
        ),
    ]
