# Generated by Django 4.1.7 on 2023-03-06 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos')),
                ('vision', models.CharField(blank=True, max_length=250)),
                ('mission', models.CharField(blank=True, max_length=500)),
                ('num_employees', models.CharField(max_length=20)),
                ('founded', models.CharField(max_length=4, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1)])),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
