# Generated by Django 4.1.7 on 2023-03-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='founded',
            field=models.CharField(max_length=4),
        ),
    ]
