# Generated by Django 4.1.7 on 2023-04-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
