# Generated by Django 4.1.7 on 2023-04-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='user',
        ),
    ]
