# Generated by Django 4.1.7 on 2023-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_orgprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
