# Generated by Django 4.1.7 on 2023-03-08 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satsified', models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('period', models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('occupation', models.CharField(choices=[('EMP', 'Employee'), ('STUD', 'Student')], max_length=20)),
            ],
        ),
    ]
