# Generated by Django 4.1.7 on 2023-04-24 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.orgprofile'),
        ),
    ]
