# Generated by Django 4.1.7 on 2023-03-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='occupation',
            field=models.CharField(choices=[('EMP', 'Employee'), ('STUD', 'Student')], max_length=10),
        ),
    ]
