# Generated by Django 4.1.7 on 2023-04-15 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_survey_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="founded",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2023),
                ]
            ),
        ),
    ]
