# Generated by Django 4.1.7 on 2023-04-15 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0009_userprofile_alter_survey_organization_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfile",
            new_name="OrgProfile",
        ),
    ]
